# frozen_string_literal: true

source "https://rubygems.org"

group :development, :test do
  gem "growl"
  gem "guard"
  gem "guard-bundler"
  gem "guard-rspec"
  gem "rb-fsevent"

  gem "dotenv"

  gem "sb-omniauth-naver", path: "../"

  gem "byebug"

  gem "sinatra"

  gem "puma"
  gem "rackup"

  gem "rerun"
end
